### ISSUE TITLE
Save weights of trained SemiDense model to load them in new one

### ISSUE THREAD

**Issue by CaelynCheung1996** [josedolz/SemiDenseNet#2]
Hi Jose,
Recently I tried to used a model trained with SemiDenseNet for transfer learning. However, I was wondering how to save weights when I trained a SemiDenseNet as .npy file you mentioned in the README file. I want to use those weights in transfer learning. Thanks!

**Comment by josedolz** [comment]
Hi @CaelynCheung1996 

For that you need to access the weights of each layer by doing (for example):

```
weights_N = myLiviaNet3D.networkLayers[N].W.eval()
```

where N is the layer of interest. Then you can save that as .npy. For example you can use that from the startTraining.py file once you are satisfied with your training.

Jose.
